### ISSUE TITLE
Can't validate on 3.0

### ISSUE THREAD

**Issue by tin2tin** [iwkse/freesound#10]
I'm getting this error when validating the freesound api key:
![image](https://user-images.githubusercontent.com/1322593/134795292-780c16e5-349a-425e-a486-cbdb455fc268.png)

**Comment by tin2tin** [comment]
I'm sorry, I still get the same error after your latest update? Is it working on 3.0 alpha for you?

**Comment by iwkse** [comment]
Did you test on the freesound-2.0 branch? that's where I've added the commit

**Comment by tin2tin** [comment]
Yes. and I unzipped it. Renamed the folder "freesound". Zipped it again. And then installed it. It's when I hit the validate button I get that error.

![image](https://user-images.githubusercontent.com/1322593/134863190-a0fbb7c8-5e7a-4863-a294-7215ba9f2470.png)

**Comment by iwkse** [comment]
Strange, I don't have any errors while clicking on validate.

**Comment by tin2tin** [comment]
Did you try to copy/paste in a new api key? Maybe they changed something there?

**Comment by iwkse** [comment]
Can you try now? Should be fixed.

**Comment by tin2tin** [comment]
Cool, now it is working again. Thank you. 

For user-friendliness, maybe you could consider to make the 2.0 branch in to the master branch and ensure the folder naming will work when downloading the repository as a copy?

I noticed that if you select a file in the list, but do not play it before importing it, it'll just be one frame long strip. Should I make an additional report on this?

Oh, after throwing in a few file I got his error each and every time I try to import a file: 
![image](https://user-images.githubusercontent.com/1322593/134904840-0dd75fdc-ebdf-4a67-a565-5fd1ec461e0e.png)

Btw.  if you use Blender for sound work, you may have an interest in this add-on: https://github.com/tin2tin/audacity_tools_for_blender

**Comment by iwkse** [comment]
Yes I was thinking already about merging to master, I just did it. As for the next issues, yes please, open a separate issue. Thank you for your link and report!
