### ISSUE TITLE
.aiff/.aif breaks import

### ISSUE THREAD

**Issue by tin2tin** [iwkse/freesound#14]
After importing .aiff/.aif the following imports fails with this error:
![image](https://user-images.githubusercontent.com/1322593/134941574-df021683-d21c-478e-9bba-709379242f5d.png)

**Comment by iwkse** [comment]
What's the file you're searching?

**Comment by tin2tin** [comment]
Just search for aiff.

**Comment by iwkse** [comment]
It happens only for HQ, seems like it's not getting properly the flag to be HQ
