### ISSUE TITLE
Some sound design using the freesound add-on

### ISSUE THREAD

**Issue by tin2tin** [iwkse/freesound#16]
Did some sound design with your freesound add-on: https://blender.chat/file-upload/9WpYWJ5WwdGQFdzQ5/0000-0644.mp4
It was quite fun with the add-on. I did some final touches with the audacity-pipe.

I just want to mention this, as the errors I encountered, are the ones I already mentioned here. So that quite assuring, I think.

**Comment by tin2tin** [comment]
I tweeted the video with a link to your add-on. So far 5000 have seen it, so hopefully, your great add-on will get a bit of well deserved attention.

**Comment by iwkse** [comment]
Thanks a lot! I will have time this weekend to fix bugs you're reported. Thank you very much. Beside that, your video is quite astonishing, wonderful!
