### ISSUE TITLE
Add strip with display waveform On

### ISSUE THREAD

**Issue by samytichadou** [iwkse/freesound#20]
Knowing that strips from freesound will likely be cutted and trimmed in the blender vse, it could be useful to have this as an option (preferences ?)
Cheers, thanks for this addon !

**Comment by iwkse** [comment]
Sorry I didn't get it well. Do you mean to cut the strip before inserting it?

**Comment by samytichadou** [comment]
No I mean "enable waveform" strip property toggled on by default when importing a freesound strip in the vse time-line (at least as an option) could be a time-saver.

**Comment by iwkse** [comment]
Got it now. I don't know if it's really needed such option as the strip already has. I wouldn't duplicate it. Maybe to switch it on by default but it might slow things down when many strips. I would probably leave it as it is since it's quite simple to do it from the strip itself.

**Comment by samytichadou** [comment]
I may not have been clear enough here. My point of view is, when i add sound strips from freesound in my timeline in VSE, I always have to go to the "strip" category in the side bar, enable the waveform display (blender native option), then go back to my freesound category. I find this pretty annoying, knowing using this addon, I will probably get some sounds to trim them precisely, delete them, trying another one... This "display waveform" option would allow more efficiency, and could be a settings (preference or scene settings) off by default (the behavior would not be changed), but the user could choose. 
And for the risk of slowing things down, the user could deactivate them after working on them... The waveform today is pretty ok performance wise i think (at least on my workstation).
Cheers !

**Comment by iwkse** [comment]
I understand, i think when this works it's going to make it easier: #18

**Comment by samytichadou** [comment]
> I understand, i think when this works it's going to make it easier: #18

Don't think it will really help, this issue adds a preview for the user to get a hint of the sound itself, the "display waveform" option in blender would help user to work the sound in the timeline, trim it...

**Comment by iwkse** [comment]
If you click on the overlays, you have waveform display > waveforms on

**Comment by samytichadou** [comment]
Yep I know, so no chance to see this feature in your add-on? With a pr or something?

**Comment by iwkse** [comment]
Why do you need such option in the add-on if it's already available in Blender?

**Comment by samytichadou** [comment]
Here is my usecase : 

https://user-images.githubusercontent.com/26276003/146687198-06041966-c7a6-4e58-a089-af094dd74722.mp4

I find it a repetitive and non efficient task to click the "display waveform" option every time, especially with the current "category problem" in blender (crowded sidebar). An option to have it by default on import would be a good workaround i think...

**Comment by iwkse** [comment]
Yes, I understood, but why this doesn't work for you?

https://blenderartists.org/uploads/default/original/4X/c/6/d/c6de159793eb8c9756abd855f16b2ec276f4cf96.png

**Comment by samytichadou** [comment]
I use the blender default behavior, which prevents the vse to be laggy by showing only waveform of strips with option on : 
![image](https://user-images.githubusercontent.com/26276003/146694882-afdd0b8a-cfa2-4e31-9b8a-01e420e16bd8.png)

I find it to be the best settings for blender editing, and i think audio strips from freesound, which almost always have to be edited could benefits of having this per-strip option on (as an option in this addon) don't you think ?

What is your take on that ? what would prevent you to add or accept a pr of this as a user option ? I don't find any bad side about this option, but i may be missing something ?
