### ISSUE TITLE
Error when enable 

### ISSUE THREAD

**Issue by tin2tin** [iwkse/freesound#7]
When enabling the add-on I get this error in 2.83:
![image](https://user-images.githubusercontent.com/1322593/78527854-4b6b7500-77de-11ea-874a-58eb81ac5c63.png)

**Comment by iwkse** [comment]
The plugin folder should be freesound. It's freesound-freesound-2 in your case

**Comment by tin2tin** [comment]
Maybe you can make a release with the correct folder names?
